# Generated by Django 4.2.7 on 2024-01-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the author', max_length=100, verbose_name="Author's first name")),
                ('last_name', models.CharField(help_text='Enter the last name of the author', max_length=100, verbose_name="Author's last name")),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter the date of birth', null=True, verbose_name='The date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter the date of death', null=True, verbose_name='The date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the book', max_length=200, verbose_name='Book name')),
                ('summary', models.TextField(help_text='Enter a short summary', max_length=1000, verbose_name='Book summary')),
                ('isbn', models.CharField(help_text='Must contain 13 symbols', max_length=13, verbose_name='Book ISBN')),
                ('author', models.ManyToManyField(help_text='Choose the author of the book', null=True, to='catalog.author', verbose_name='Book author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the genre of the book', max_length=200, verbose_name='Book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language of the book', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the status of the book', max_length=20, verbose_name='Book status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Enter the inventory number of the book instance', max_length=20, null=True, verbose_name='Book instance inventory number')),
                ('imprint', models.CharField(help_text='Enter the publisher and the year of release', max_length=200, verbose_name='Book publisher and year of release')),
                ('due_back', models.DateField(blank=True, help_text='Enter the instance due back', null=True, verbose_name='Book instance due back')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change the status of the book instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Book instance status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose the genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Book genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Book language'),
        ),
    ]
