# Generated by Django 4.2.7 on 2024-01-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Choose the author of the book', to='catalog.author', verbose_name='Book author'),
        ),
    ]
